name: PR Checks

on:
  pull_request:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_actions:
    name: Run Check Actions
    uses: ./.github/workflows/check_actions.yml
    permissions:
      security-events: write # Needed to generate and security alerts for actions in this repo.
